{"name": "test_api", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'new_pet.json'", "trace": "def test_api():\n        with allure.step('Add new pet to store'):\n>           PetStoreApi.add_new_pet()\n\ngroup1\\test_group_1.py:73: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    @staticmethod\n    def add_new_pet():\n>       with open(\"new_pet.json\") as json_load:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'new_pet.json'\n\ngroup1\\api_petstore.py:9: FileNotFoundError"}, "steps": [{"name": "Add new pet to store", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'new_pet.json'\n", "trace": "  File \"C:\\Users\\ikram\\PycharmProjects\\FinalProject\\group1\\test_group_1.py\", line 73, in test_api\n    PetStoreApi.add_new_pet()\n  File \"C:\\Users\\ikram\\PycharmProjects\\FinalProject\\group1\\api_petstore.py\", line 9, in add_new_pet\n    with open(\"new_pet.json\") as json_load:\n"}, "start": 1660671327490, "stop": 1660671327490}], "start": 1660671327489, "stop": 1660671327491, "uuid": "975443a4-585a-410a-9e7e-9254cdd9c7c6", "historyId": "e159269fde59a21ce1aa1a669d46d0d4", "testCaseId": "b7a85fe41ede488f9b42aa584f070199", "fullName": "group1.test_group_1#test_api", "labels": [{"name": "parentSuite", "value": "group1"}, {"name": "suite", "value": "test_group_1"}, {"name": "host", "value": "DESKTOP-919U1VN"}, {"name": "thread", "value": "15552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "group1.test_group_1"}]}